### ISSUE TITLE
Shows loot type after every raid mob/trash, it is very annoying.

### ISSUE THREAD

**Issue by csolaszol86** [Tauri-WoW-Community-Devs/oqueue#6]
We were raiding in soo.

It warned me continuously about group loot. 
The loot type was not changed.

**Comment by Maczuga** [comment]
So a few things:

1. When exacly was it warning? After boss kills? After zoning in/out? After somebody left/joined the group?
2. Which difficulty it was - so: 10N/10H/25N/25H/Flex/LFG?
3. Did you click the "Accept" button or simply ignored?
4. What is your client locale?

**Comment by Maczuga** [comment]
Also need to know - which difficulty it was - so:
10N/10H/25N/25H/Flex/LFG?

**Comment by Maczuga** [comment]
And one more - did you click the "Accept" button or simply ignored? Just tested it and once I pressed "Accept" it never appeared again.

**Comment by csolaszol86** [comment]
1.) I was in Siege of Orgrimmar. We started trash killing with some people. This happened on trash.
I was killing thrash, others might have come in the instance during that. I don't think anybody was invited during that period, we waited for some people, he leader was in combat, so he couldn't invite people. Nobody left the raid. I disabled the addon for the boss kills.
2.) 25 HC difficulty
3.) I tried to press accept, but it pop up right after accept with the same loot type. I tried to close the window, but it still pop up after that whit the same loot type.
4.) EN GB

**Comment by Maczuga** [comment]
Ok, I am gonna add some debug messages for that. 

Please download this version: https://github.com/Tauri-WoW-Community-Devs/oqueue/releases/download/v0.0.3a/oqueue.zip

![image](https://user-images.githubusercontent.com/544349/83395957-78619000-a3fb-11ea-845d-a4762a813be5.png)

Each time the loot method change dialog appears - click ":Accept".
If you'll get the issue with loot popup spam - please take a screenshot of what's printed in chat.

The most important part for me is between:

#&#8203;6 - start
...
#&#8203;6 - end

Also - this might have been fixed with v0.0.3 - but as it didn't happen to me it would be best if you could test it.

**Comment by csolaszol86** [comment]
I got this error today, if it helps anything. This is with the V0.0.3a version.

1x oqueue\oqueue-1.9.5.lua:12533: bad argument #1 to 'tostring' (value expected)
[C]: in function `tostring'
oqueue\oqueue-1.9.5.lua:12533: in function `log'
oqueue\oqueue-1.9.5.lua:742: in function `?'
oqueue\oqueue-1.9.5.lua:24164: in function <oqueue\oqueue.lua:24161>

Locals:
echo = "This debug message is related to issue #6"
now = 1591005533
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = "|cFF00B00011:47:59|r  |cFF808080logged on|r Peekay-[HU] Tauri WoW Server |cFF808080v1.9.5 (hu)|r"
 2 = "|cFF00B00011:50:07|r  entering |cFFE0E000Siege of Orgrimmar|r"
 3 = "|cFF00B00011:50:57|r  Instance lasted 0:47"
 4 = "|cFF00B00011:51:45|r  entering |cFFE0E000Siege of Orgrimmar|r"
}
(*temporary) = "|cFF00B000"
(*temporary) = "11:58:53"
(*temporary) = "|r  "
oq = <table> {
 hint_next = <function> defined @oqueue\oqueue.lua:16413
 update_scores = <function> defined @oqueue\oqueue.lua:21236
 add_voip_subselection = <function> defined @oqueue\oqueue.lua:14249
 route_to_boss = <function> defined @oqueue\oqueue.lua:23340
 on_top_dps_recvd = <function> defined @oqueue\oqueue.lua:19424
 queue_popped = <function> defined @oqueue\oqueue.lua:23891
 onShow_tab1 = <function> defined @oqueue\oqueue.lua:13809
 calc_pkt_stats = <function> defined @oqueue\oqueue.lua:3937
 set_deserter = <function> defined @oqueue\oqueue.lua:20883
 send_q = <table> {
 }
 pending = <table> {
 }
 decode_hp = <function> defined @oqueue\oqueue.lua:21742
 player_new_level = <function> defined @oqueue\oqueue.lua:24861
 get_scanning_tooltip = <function> defined @oqueue\oqueue.lua:11655
 get_bg_experience = <function> defined @oqueue\oqueue_premade_info.lua:356
 find_first_empty_slot = <function> defined @oqueue\oqueue.lua:22445
 clear_report_attempts = <function> defined @oqueue\oqueue.lua:25375
 waitlist = <table> {
 }
 group_left = <function> defined @oqueue\oqueue.lua:8660
 long_tooltip = oqlongtooltip {
 }
 get_spell_crit = <function> defined @oqueue\oqueue.lua:3118
 tab3_enforce = oq_check {
 }
 create_tab_banlist = <function> defined @oqueue\oqueue.lua:15808
 raid = <table> {
 }
 pass_preference_filter = <function> defined @oqueue\oqueue.lua:12359
 space_it = <function> defined @oqueue\oqueue.lua:5939
 raid_announce_relay = <function> defined @oqueue\oqueue.lua:6734
 pm_tooltip_set = <function> defined @oqueue\oqueue_tooltips.lua:834
 first_open_seat = <function> defined @oqueue\oqueue.lua:24183
 make_dropdown_premade_subtype_selector = <function> defined @oqueue\oqueue.lua:14122
 trim_oldies = <function> defined @oqueue\oqueue.lua:18819
 send_to_scorekeeper = <function> defined @oqueue\oqueue.lua:4749
 create_scenario_group = <function> defined @oqueue\oqueue.lua:9420
 announce_raid_leader = <function> defined @oqueue\oqueue.lua:18166
 start_ready_check = <function> defined @oqueue\oqueue.lua:19971
 cell_occupied = <function> defined @oqueue\oqueue.lua:8942
 _instance_end_tm = 0
 player_died = <function> defined @oqueue\oqueue.lua:24843
 update_raid_listitem = <function> defined @oqueue\oqueue.lua:18689
 get_premade_type_desc = <function> defined @oqueue\oqueue.lua:14505
 on_update_instance_info = <function> defined @oqueue\oqueue.lua:344
 show_btags = <function> defined @oqueue\oqueue.lua:6442
 on_group_roster_update = <function> defined @oqueue\oqueue.lua:24706
 toggle_auto_role = <function> defined @oqueue\oqueue.lua:24397
 bg_name = <function> defined @oqueue\oqueue.lua:7787
 get_arena_ratio = <function> defined @oqueue\oqueue_premade_info.lua:426
 decode_stats2 = <function> defined @oqueue\oqueue.lua:22098
 init_stats_element = <function> defined @oqueue\oqueue.lua:5099
 get_arena_rating = <function> defined @AddO

**Comment by query-csharp** [comment]
thank you for your report @csolaszol86  we'll investigate and roll out a hotfix asap

**Comment by Maczuga** [comment]
@csolaszol86 Sorry, did a typo in logging.

https://github.com/Tauri-WoW-Community-Devs/oqueue/releases/download/v0.0.3b/oqueue.zip

Try this.

**Comment by csolaszol86** [comment]
I did not try it in raid, but in 5 man dungeon, the notification window does not pop up, when changing loot type.

**Comment by Maczuga** [comment]
Currently only raids (10N,25N,10H,25H) have this enabled.
Might enable this for dungeons too (since dungeons and old raids share difficultyIndex anyway).

**Comment by csolaszol86** [comment]
I just disbanded a premade group and this appeared in say chat:
[15:06:19.284] nil f5kYN GfT5k2

**Comment by query-csharp** [comment]
That is just debug code, don't worry, no one sees it except you :)

**Comment by Maczuga** [comment]
Some old code from here it seems:
https://github.com/Tauri-WoW-Community-Devs/oqueue/commit/666414c06dd3d30828b4062a022871f41fd8d43e#diff-bc2fb813cc67517cb4bedbf109cebb6fR6840

Will remove it and enable the loot window for dungeons and 40 man raids.

**Comment by Maczuga** [comment]
https://github.com/Tauri-WoW-Community-Devs/oqueue/releases/download/v0.0.3c/oqueue.zip

Should fix https://github.com/Tauri-WoW-Community-Devs/oqueue/issues/6#issuecomment-636850861 + enable loot window in dungeons + 40man raids

**Comment by csolaszol86** [comment]
Still not good. We were raiding today, and i received the loot type change popup several times during bossfight. SoO 25 HC with 23 man. Loot type was not changed, it remained on groop loot. People were not invited, nor did they leave the raid.

**Comment by Maczuga** [comment]
That's why I needed a screenshot of what appears in chat during that. If you are on the newest version - you should receive something like this:

![image](https://user-images.githubusercontent.com/544349/83438613-01031f00-a442-11ea-9428-0397672c72aa.png)

This message will appear each time this window pops up.

**Comment by csolaszol86** [comment]
Hi, 
I went to an RHC today and i received the loot type popup windows constantly.

Chat printout:
[14:48:38.828] [OQUEUE] #6 - start
[14:48:38.828] [OQUEUE] Previous loot method:  nil
[14:48:38.828] [OQUEUE] Current loot method:  needbeforegreed
[14:48:38.828] [OQUEUE] #6 - end
[14:48:39.762] <Deadly Boss Mods> Heroic - Darkmaster Gandling down after 34 seconds! This is a new record! (Old record was 34 seconds). You have 7 total victories.
[14:48:39.847] [OQUEUE] This debug message is related to issue #6
[14:48:39.847] [OQUEUE] If you see the loot type change message too often - please show report the results below to our Github
[14:48:39.847] [OQUEUE] #6 - start
[14:48:39.847] [OQUEUE] Previous loot method:  nil
[14:48:39.847] [OQUEUE] Current loot method:  needbeforegreed
[14:48:39.847] [OQUEUE] #6 - end
[14:48:40.897] [OQUEUE] This debug message is related to issue #6
[14:48:40.897] [OQUEUE] If you see the loot type change message too often - please show report the results below to our Github
[14:48:40.897] [OQUEUE] #6 - start
[14:48:40.897] [OQUEUE] Previous loot method:  nil
[14:48:40.897] [OQUEUE] Current loot method:  needbeforegreed
[14:48:40.897] [OQUEUE] #6 - end

**Comment by csolaszol86** [comment]
[oqueue loot type popup window and text printout screenshoot](https://www.dropbox.com/s/qcvm4jf6n0ht9w9/oqueue%20loot%20type.png?dl=0)
