### ISSUE TITLE
Addon update warning

### ISSUE THREAD

**Issue by query-wow** [Tauri-WoW-Community-Devs/oqueue#7]
Trying to find a way to announce a new oqueue update. I think there's an in built system for this already.

**Comment by Maczuga** [comment]
Doesn't that work by checking addon version on listed premades + sending info between bnet friends?

**Comment by query-csharp** [comment]
Might be the case, i'll be checking for it in the code

**Comment by query-csharp** [comment]
Closed in https://github.com/Tauri-WoW-Community-Devs/oqueue/commit/aca4f95c203c7097bb7a1b4cbfcc7d0fc485f499
